ALTER TABLE classes ADD COLUMN IF NOT EXISTS semester VARCHAR(50);
ALTER TABLE classes ADD COLUMN IF NOT EXISTS subject_name VARCHAR(150);
ALTER TABLE classes ADD COLUMN IF NOT EXISTS credits DOUBLE PRECISION;
